### ISSUE TITLE
MSTile files are generated with 2 dots

### ISSUE THREAD

**Issue by bogdan-nourescu** [101arrowz/parcel-plugin-pwa-manifest#1]
Normally it wouldn't be a problem to generate the mstile files with 2 dots, but if you try to deploy to Google AppEngine they won't allow it.
`ERROR: (gcloud.app.deploy) INVALID_ARGUMENT: Filename cannot contain '.', '..', '\r', start with '-', '_ah/', or '\n': mstile-150x150..44f23636.png`
The fix is really easy, you have to remove the extra dot from hashedFilename before the ".png"
I can make a pull request if you like.

**Comment by 101arrowz** [comment]
Hi! If you'd like I can fix this myself, but you're more than welcome to make a PR!
