### ISSUE TITLE
Emit event after finish [FEATURE REQUEST]

### ISSUE THREAD

**Issue by bogdan-nourescu** [101arrowz/parcel-plugin-pwa-manifest#5]
## The problem
What can't you do right now that you want added as a new feature?

I have a build pipeline that needs to know when the icons are generated and the build is finished so it can deploy the app to production

## Possible solution
If you have any idea for a possible solution, please write it here.

Emit an event (something like pwa-finished /pwa-builtend/ pwa-bundled)
I've done something similar in my fork: https://github.com/CBN-IT/parcel-plugin-pwa-manifest

**Comment by 101arrowz** [comment]
Thanks for the suggestion!
